spring:
  application:
    name: api
  datasource:
    url: jdbc:postgresql://localhost:5432/postgres
    username: postgres
    password: postgres
  jpa:
    hibernate:
      ddl-auto: validate
    show-sql: true
    properties:
      hibernate:
        format_sql: true
logging:
  file:
    name: ./var/logs.log

server:
  port: 80

token:
  signing:
    key: sdfsdhfgusdhiufshdufghuisdugfhsudhguhsdufhgu
